### ISSUE TITLE
Breaks when using null or undefined values

### ISSUE THREAD

**Issue by r-inaldi** [jackfranklin/test-data-bot#146]
It'd be good to support these values.

Error

`TypeError: Cannot read property 'generatorType' of null`

Stacktrace:

```
 at isGenerator (node_modules/@jackfranklin/test-data-bot/src/index.ts:62:36)
 at expandConfigField (node_modules/@jackfranklin/test-data-bot/src/index.ts:103:9)
 at node_modules/@jackfranklin/test-data-bot/src/index.ts:90:16
```

Is this on purpose? Otherwise, let me know I can open a PR to fix it.

**Comment by merykozlowska** [comment]
A workaround until the fix is merged & released: `perBuild(() => null)`.

**Comment by ironosity** [comment]
Sadly, this workaround doesn't work if you use builders to build fields where the field builders have null field.. :(
