### ISSUE TITLE
Sequence return type 

### ISSUE THREAD

**Issue by JaysQubeXon** [jackfranklin/test-data-bot#155]
Hi,

Thank you for refactoring for Typescript support.

I'm getting 

```
Argument of type '(x: number) => string' is not assignable to parameter of type '(counter: number) => number'.
  Type 'string' is not assignable to type 'number'.
```

with a simple: 

```
fields: {
   email: sequence((x) => `jack${x}@test.com`),
}
```

Your readme doc does use the same exact example.

any help is appreciated,
Thank you.

**Comment by jackfranklin** [comment]
Thanks! I think this is definitely a bug. We could type it as `number => unknown` which I think would help here. I'll try to reproduce this locally and get a fix up.
