### ISSUE TITLE
Traits?

### ISSUE THREAD

**Issue by jackfranklin** [jackfranklin/test-data-bot#17]
Factory bot supports traits, so you can do this:

```
user = create(:user, :is_admin)
```

And in the factory you've told it what `:is_admin` should set. I wonder if something like this is useful for test-data-bot:

```js
const userBuilder = build('User').fields({
  name: fake(f => f.name.findName()),
  is_admin: false,
}).trait('is_admin', {
  is_admin: true,
})
```

At which point, doing:

```js
const user = userBuilder() // not admin
const admin = userBuilder('is_admin', {...})
```

Would be quite a nice API, I think.

**Comment by julionav** [comment]
I love the idea! I've been working with [factory bot](https://github.com/thoughtbot/factory_bot/blob/master/GETTING_STARTED.md) with rails and this library for my frontend testing and traits is the only thing I feel is missing.
I could make a PR for that

**Comment by jackfranklin** [comment]
This needs some more thinking about now v1 is out but I think I'd like to support this in some form. Hmmmmmmm.
