### ISSUE TITLE
Stable Faker

### ISSUE THREAD

**Issue by cassiozen** [jackfranklin/test-data-bot#177]
Having faker built-in is great, but in some cases it would be useful to get each build's random values stable (For snapshot testing, for example). 

Faker already accepts a seed, it would be awesome if there were an option to automatically seed per build: In other words, every individual build would have a unique seed, so even though multiple sequential builds would be different among each other, when generated again, they would remain the stable.

**Comment by jackfranklin** [comment]
Hey @cassiozen this sounds like a great idea but I'm struggling to picture the implementation. I think the default behaviour would stay the same, but then you could have a flag that would tell test-data-bot to use a seed for a particular call?

```js
const user = userBuilder({ seed: 1234 })
```

And that way any user built with that seed would return the same faker data? Is that what you mean?

**Comment by cassiozen** [comment]
My original idea was having an option for creating the builder, something like:

```js
const userBuilder = build('User', {
  options: {
    seededFaker: true // would keep an internal sequential counter used as seed
  },
  fields: {
    name: fake(f => f.name.findName()),
  },
});
```

But your suggestion looks better 🤣

**Comment by cassiozen** [comment]
I've been looking at the code to try to put a PR together, but the difficulty right now is that `faker` exports an instance instead of the constructor function, therefore applying a seed will be persistent across all faker calls.

**Comment by jackfranklin** [comment]
Hmmm - I wonder if we could use our `fake` function to support this?

```
fake(f => f.blah()) // different every time
fake(f => f.blah(), {stable: true}) // `fake` remembers the return of the function and returns it next time
```

WDYT?

**Comment by cassiozen** [comment]
I would gladly use this suggestion, as it solves my personal issue (and as it seems it's the best thing  that can be done given the circumstances.)

I have to say, though, that the nice thing about having the seed be sequential is that it's stable across runs while still allowing for generating multiple different/unique objects in my tests. I looked into making a PR on faker, but they seem to be not-very-active (132 open PRs) - crazy thought: Maybe forking faker?

**Comment by jackfranklin** [comment]
Hey @cassiozen sorry for my silence; re-reading this back I'm not sure if this is worth adding or not. Please could you explain to me if you want to have most builders use a fake but occassionally have them stick to a specific value could you not override that?

```js
const user = userBuilder({
  overrides: { name: 'jack' }
});
```

Where `name` is normally a fake but in this case you hardcode it? That might be the best solution here if it's hard to get that seed through to Faker. And I'm not super keen on forking faker :)

**Comment by lughino** [comment]
Hey @jackfranklin ,
I ran into the same need.
Basically, I have 3 fields that should have the same fixture:
```javascript
{
  fields: {
    firstName: fake((f) => f.name.firstName()),
    lastName: fake((f) => f.name.lastName()),
    email: fake(
      (f) => `${f.name.firstName().toLowerCase()}.${f.name.lastName().toLowerCase()}@sample.com`,
    ),
  }
}
```

The problem is that without having control of the fixture I cannot match the data in the right way.

**Comment by pbeshai** [comment]
My workaround for this is using a separate faker that I can seed.

```js
const faker = require('faker');
const { build, fake, oneOf } = require('@jackfranklin/test-data-bot');

const countBuilder = build({
  fields: {
    // use faker instead of `f`
    count: fake(() => faker.random.number()), // seeded
    other: fake((f) => f.random.number()), // not seeded
  },
});

describe('something', () => {
  it('other', () => {
    faker.seed(100);
    count = countBuilder();
  });
});
```

Not sure if there are issues with this yet, but it seeds as I expect

**Comment by jackfranklin** [comment]
@pbeshai nice, I think that's a good solution!

Given this can be done via the options we have now, I don't think it's worth an API change to do this but please open an issue if you're reading this and strongly disagree.
