### ISSUE TITLE
Override do not allow null nor zero

### ISSUE THREAD

**Issue by hidalgofdz** [jackfranklin/test-data-bot#287]
Overrides currently don't allow to pass 0 or null as a value. I think test-data-bot should allow at least to pass 0 as an override.

**Comment by kimroen** [comment]
This also goes for empty strings, which are not allowed as overrides.

**Comment by kimroen** [comment]
If we just wanted to allow values (like `0` or empty string, but not `null` or `undefined`), then we could use `??` instead of `||`:

```ts
const valueOrOverride = overrides[fieldKey] ?? traitOverrides[fieldKey] ?? fieldValue;
```

**Comment by hidalgofdz** [comment]
Should the library allow to override a value with undefined ?

**Comment by kimroen** [comment]
> Should the library allow to override a value with undefined ?

I'm not sure. At the moment it's not possible to remove a key in an override, so it wouldn't conflict in that sense. But maybe doing so should be possible?

The fact that both reading missing keys and reading keys that contain `undefined` return `undefined` is a bit of a problem some times.

**Comment by jackfranklin** [comment]
This should work as of v1.4.0.
