### ISSUE TITLE
Typescript definitions

### ISSUE THREAD

**Issue by Lughino** [jackfranklin/test-data-bot#52]
Hi @jackfranklin !
Really great and useful module!

It would be really really useful to have the typescript definitions of this module, for typescript and javascript users as well.

**Comment by jackfranklin** [comment]
Hi @Lughino ,

Glad you like the module. I think the best thing here is probably to rebuild in TypeScript, rather than maintain a separate definitions file. I'm a big TS fan these days :)

I'll try to do this but don't know when, someone else should feel free to if they feel particularly keen.

**Comment by vladferix** [comment]
I just quickly implemented these definitions by myself, not sure if they are fully correct, but they serve my needs:
`
/// <reference types="faker" />

declare module "test-data-bot" {
  export type BuilderFunction<T> = (overrideFields?: Partial<T>) => T;
  export type BuilderValue<T> = ((...args: any[]) => T) | T;

  export interface Builder<T extends object> extends BuilderFunction<T> {
    fields(fieldsParams: { [K in keyof T]: BuilderValue<T[K]> }): Builder<T>;
    map(fieldsParams: { [K in keyof T]: BuilderValue<T[K]> }): Builder<T>;
  }

  export function build<T extends object>(name?: string): Builder<T>;
  export function bool(): boolean;
  export function incrementingId(): number;
  export function sequence<T>(sequenceFn: (id: number) => T): T;
  export function perBuild<T>(buildFn: (...args: any[]) => T): T;
  export function oneOf<T>(...oneOfOptions: T[]): T;
  export function numberBetween(min: number, max: number): number;
  export function arrayOf<T>(builder: BuilderValue<T>, count: number): T[];
  export function fake<T>(fakeFn: (f: Faker.FakerStatic) => T): T;
}
`

**Comment by jackfranklin** [comment]
@vladferix oh awesome! I'd welcome a PR that adds those to be published (I don't quite know how best to do that) as an interim solution.

**Comment by Lughino** [comment]
@jackfranklin I'm considering to rewrite this module in typescript.
Do you have any thoughts about the tooling?

- tsc or babel 7
- tslint which configuration (I still don't feel ok using eslint with typescript, I wish to use it but it's not 100% ready yet)

**Comment by jackfranklin** [comment]
@Lughino great to hear!

I feel quite strongly that we should go for `tsc` exclusively, and `eslint-typescript`. It may not be perfect yet but it feels more future proof.

Let me know if you're working on this; else I may get to it soon :)

**Comment by vladferix** [comment]
Is anyone working on porting test-data-bot to typescript? I am also can try to find some time to work on porting, or at least try to figure out and create MR with typings

**Comment by jackfranklin** [comment]
@vladferix it's on my list to build soon, I think. I want to make some (minor) API changes so this feels like a good chance to do a TS rebuild.

**Comment by vladferix** [comment]
Okay, in case of some help needed with typescript, I can try to help

**Comment by 0vidiu** [comment]
@vladferix Correct me if I'm wrong but the `.map()` method does not have the correct type (the `.map()` method takes a function as its argument.). Here's what I had to do to make it work. This might be helpful to others as well.

```ts
/// <reference types="faker" />

declare module 'test-data-bot' {
  export type BuilderFunction<T> = (overrideFields?: Partial<T>) => T;
  export type BuilderValue<T> = ((...args: any[]) => T) | T;

  export interface Builder<T extends object> extends BuilderFunction<T> {
    fields(fieldsParams: { [K in keyof T]: BuilderValue<T[K]> }): Builder<T>;
    map(
      mapFn: (
        fieldsParams: { [K in keyof T]: BuilderValue<T[K]> }
      ) => BuilderValue<T[K]>
    ): Builder<T>;
  }

  export function build<T extends object>(name?: string): Builder<T>;
  export function bool(): boolean;
  export function incrementingId(): number;
  export function sequence<T>(sequenceFn: (id: number) => T): T;
  export function perBuild<T>(buildFn: (...args: any[]) => T): T;
  export function oneOf<T>(...oneOfOptions: T[]): T;
  export function numberBetween(min: number, max: number): number;
  export function arrayOf<T>(builder: BuilderValue<T>, count: number): T[];
  export function fake<T>(fakeFn: (f: Faker.FakerStatic) => T): T;
}
```

**Comment by vladferix** [comment]
@0vidiu  Sinse my last post I already did few iterations of improvement test-data-bot typings for my project. Here is my latest iteration. You can try it and give your feedback
`/// <reference types="faker" />

declare module "test-data-bot" {
  export type BuilderFunction<T> = (overrideFields?: Partial<T>) => T;
  export interface Generator<T> {
    generate: () => T;
  }

  export type BuilderPrimitiveValue<T> = T | Generator<T> | Builder<T>;
  export type BuilderValue<T> = DeepBuilderValue<BuilderPrimitiveValue<T>>;

  export type DeepBuilderValue<T> = T extends any[]
    ? Array<DeepBuilderValueArray<T[number]>>
    : T extends object
    ? { readonly [P in keyof T]: T[P] }
    : T;

  export interface Builder<T extends object> extends BuilderFunction<T> {
    fields(fieldsParams: { [K in keyof T]: BuilderValue<T[K]> }): Builder<T>;
    map(fn: (fieldsParams: Pick<T, K>) => Pick<T, K>): Builder<T>;
  }

  export function build<T extends object>(name?: string): Builder<T>;
  export function bool(): Generator<boolean>;
  export function incrementingId<T extends number>(): Generator<T>;
  export function sequence<T>(sequenceFn: (id: number) => T): Generator<T>;
  export function perBuild<T>(buildFn: (...args: any[]) => T): Generator<T>;
  export function oneOf<T>(...oneOfOptions: T[]): Generator<T>;
  export function numberBetween(min: number, max: number): Generator<number>;
  export function arrayOf<T>(builder: BuilderValue<T>, count: number): Generator<T[]>;
  export function fake<T>(fakeFn: (f: Faker.FakerStatic) => T): Generator<T>;
}
`

**Comment by spykr** [comment]
> @0vidiu Sinse my last post I already did few iterations of improvement test-data-bot typings for my project. Here is my latest iteration. You can try it and give your feedback
> 
> ```ts
> /// <reference types="faker" />
> 
> declare module "test-data-bot" {
>   export type BuilderFunction<T> = (overrideFields?: Partial<T>) => T;
>   export interface Generator<T> {
>     generate: () => T;
>   }
> 
>   export type BuilderPrimitiveValue<T> = T | Generator<T> | Builder<T>;
>   export type BuilderValue<T> = DeepBuilderValue<BuilderPrimitiveValue<T>>;
> 
>   export type DeepBuilderValue<T> = T extends any[]
>     ? Array<DeepBuilderValueArray<T[number]>>
>     : T extends object
>     ? { readonly [P in keyof T]: T[P] }
>     : T;
> 
>   export interface Builder<T extends object> extends BuilderFunction<T> {
>     fields(fieldsParams: { [K in keyof T]: BuilderValue<T[K]> }): Builder<T>;
>     map(fn: (fieldsParams: Pick<T, K>) => Pick<T, K>): Builder<T>;
>   }
> 
>   export function build<T extends object>(name?: string): Builder<T>;
>   export function bool(): Generator<boolean>;
>   export function incrementingId<T extends number>(): Generator<T>;
>   export function sequence<T>(sequenceFn: (id: number) => T): Generator<T>;
>   export function perBuild<T>(buildFn: (...args: any[]) => T): Generator<T>;
>   export function oneOf<T>(...oneOfOptions: T[]): Generator<T>;
>   export function numberBetween(min: number, max: number): Generator<number>;
>   export function arrayOf<T>(builder: BuilderValue<T>, count: number): Generator<T[]>;
>   export function fake<T>(fakeFn: (f: Faker.FakerStatic) => T): Generator<T>;
> }
> ```

Thank you for the types @vladferix, however when I use them I'm getting a few errors. I'm very new to TypeScript so I'm not sure if it's a version compatibility or how to fix them. If you have the time could you please advise?

```
ERROR in ~/src/test-data-bot.d.ts(9,69):
TS2344: Type 'T' does not satisfy the constraint 'object'.
ERROR in ~/src/test-data-bot.d.ts(13,13):
TS2304: Cannot find name 'DeepBuilderValueArray'.
ERROR in ~/src/test-data-bot.d.ts(20,36):
TS2304: Cannot find name 'K'.
ERROR in ~/src/test-data-bot.d.ts(20,51):
TS2304: Cannot find name 'K'.
```
