### ISSUE TITLE
Cretit card information is availabe?

### ISSUE THREAD

**Issue by crisfcodes** [jackfranklin/test-data-bot#520]
I want to use `test-data-bot` to generate credit card information, according to docs, internally `test-data-bot` use [Faker js](https://github.com/Marak/faker.js) which has [Api methods](https://github.com/Marak/faker.js/blob/master/Readme.md#api-methods) to generate credit card information, especifically in `finance`, you can find `creditCardNumber` and `creditCardCVV`, if you try to use this methods, your IDE thrown an error because this methods doesnt exist in `test-data-bot` package.

how can I generate this type of information with `test-data-bot`? 

credit card cvv
credit card number
credit card expiration date

According to `faker` library [issue](https://github.com/Marak/faker.js/issues/1198#issuecomment-873369632) opened, this methods are available.

**Comment by jackfranklin** [comment]
Hello,

I've updated Faker to the latest version; in v1.4.0 hopefully this will work. Please open a new issue if it doesn't. Thanks!
