### ISSUE TITLE
Allow users to provide their own Faker

### ISSUE THREAD

**Issue by jackfranklin** [jackfranklin/test-data-bot#560]
I'm also considering a change where test-data-bot no longer provides faker, but instead you initiate it with faker, something like:

```ts
import { init } from 'test-data-bot';
import faker from 'faker';

const testDataBot = init({ faker: faker });
```

And if you didn't do that we'd fall back to whatever version of Faker test-data-bot ships with. I think it would be nice to ensure people don't need a new bump of test-data-bot to get onto the latest Faker.

Opinions welcome - maybe this is overcomplicating things?

**Comment by rluvaton** [comment]
I think it's possible if you define the version as *

At it will use whatever exist or install latest (I think)

**Comment by seanlawrenz** [comment]
This might be a moot point https://github.com/Marak/faker.js

**Comment by jackfranklin** [comment]
Closing this as v2 of this library will not include faker.
