### ISSUE TITLE
Deep merge when overriding

### ISSUE THREAD

**Issue by r-inaldi** [jackfranklin/test-data-bot#67]
Not sure if it fits in the library but I have the following data structure:

```js
export const projectBuilder = build('wsProjects').fields({
  id: incrementingId(),
  type: 'wsProjects',
  attributes: {
    createdAt: fake(f => f.date.past()),
    updatedAt: fake(f => f.date.recent()),
    description: fake(f => f.lorem.paragraph()),
    title: fake(f => f.lorem.words()),
    publicUrlKey: fake(f => f.random.uuid()),
    publicUrlScope: null,
  },
  relationships: {
    images: [],
  },
});
```

Sometimes I want a fixed title for example, but when I try to override only the title other properties inside `attributes` are all gone too, because it overrides everything.

Do you think it could be useful here?

Great lib 👍

**Comment by jackfranklin** [comment]
@r-inaldi I think I'd probably use the `map` function for this:

```
projectBuilder().map(project => ({
  ...project,
  attributes: {
    ...project.attributes,
   title: 'Specific title for this'
  }
})
```

And you could wrap that up in a little utility function. I'm not sure if this library should be responsible for this. What do you think?

**Comment by vladferix** [comment]
Once I had a slightly harder case where I wanted to have slightly modified builder base on original one. I solved the problem by creating factory function with function for patching fields. Something like that:

```javascript
const makeProjectBuilder = function(updateFieldsFn = (fields) => fields) {
    const fields = updateFieldsFn({
        id: incrementingId(),
        type: 'wsProjects',
        attributes: {
        createdAt: fake(f => f.date.past()),
        updatedAt: fake(f => f.date.recent()),
        description: fake(f => f.lorem.paragraph()),
        title: fake(f => f.lorem.words()),
        publicUrlKey: fake(f => f.random.uuid()),
        publicUrlScope: null,
        },
        relationships: {
            images: [],
        },
    });
    return build('wsProjects').fields(fields);
};

makeProjectBuilder((fields) => fields.images[0] = ImageBuilder)
```
But maybe it would be nice some kind of native api for solving similar problems.




Another problem in test-data-bot which I noticed was that in case of
```javascript
const imageBuilder = build('image').fields({ title: fake(f => f.lorem.words()) })
const image = builder({ url: "blabla" })
```
non-defined new field "url" wasn't added to the image on the construction time, which is something I wasn't expecting

**Comment by jackfranklin** [comment]
> non-defined new field "url" wasn't added to the image on the construction time, which is something I wasn't expecting

@vladferix mmm - this is a hard one because it could be a bug, you might be overriding the wrong field and have made a typo, but equally I can see this being useful. What do you think to an API that took a second object of "non defined fields that I want" ?:

```
const image = builder({}, { url: 'blahbalh' })
```

Or an API more like that that would make it more obvious that `url` isn't a standard field.

**Comment by vladferix** [comment]
I believe there is no need for additional argument in case of transition to typescript. I believe that after transition to typescript you will get automatic typo prevention, which should also understand defined optional and non-optional fields. There is should be type check for all required fields in the basic builder definition, and possibility to add some optional fields in builder call.

**Comment by jackfranklin** [comment]
@vladferix but others may not be using TS even though this module is written in it, so we should be careful not to forget those users.

**Comment by vladferix** [comment]
@jackfranklin But from the other side in case you use js and you did some typo in builder({ typofield: "blabla" }) , you will not get any feedback anyway, just eventually find out that your field is just not overriden, but totally not clear why. In this case I would rather alert somehow (maybe an exception) about this incorrect usage

**Comment by r-inaldi** [comment]
@jackfranklin your solution was exactly what I did to workaround this:

```js
const Project = custom => {
  const project = projectBuilder();
  if (custom) {
    return merge(project, custom);
  }
  return project;
};
```

Where `merge` is `lodash/merge`.
Feel free to close this issue 👍

**Comment by Julioocz** [comment]
You can leverage the `.map` method for this.
```
export const projectBuilder = build('wsProjects').fields({
    idi: incrementingId(),
    createdAt: fake(f => f.date.past()),
    updatedAt: fake(f => f.date.recent()),
    description: fake(f => f.lorem.paragraph()),
    title: fake(f => f.lorem.words()),
    publicUrlKey: fake(f => f.random.uuid()),
    publicUrlScope: null
})
.map(({ id, ...attributes} ) => ({
  attributes,
  id: project,
  type: 'wsProjects',
  relationships: {
    images: [],
  },
}))
```

Then you can override the attributes directly with `projectBuilder({title: "Nice project!"})`

**Comment by Wgil** [comment]
@jackfranklin 
> @vladferix mmm - this is a hard one because it could be a bug, you might be overriding the wrong field and have made a typo, but equally I can see this being useful. What do you think to an API that took a second object of "non defined fields that I want" ?:

I thought that adding additional fields like @vladferix example was the behavior of the function, it's just natural. 

I ended up doing which is not very nice, specially if it's for a one-time usage.
```
userBuilder.map(u => ({ ...u, extra }))
```

**Comment by jackfranklin** [comment]
Closing this as it refers to the old version - if there's feature changes / bugs in v1.1.0 regarding this, please open a new issue :)

**Comment by Dobby89** [comment]
Is there a recommended way of overriding a nested property with the latest version?
