### ISSUE TITLE
Module '"@jackfranklin/test-data-bot"' has no exported member 'fake'

### ISSUE THREAD

**Issue by RamonEspinosa** [jackfranklin/test-data-bot#688]
## Description
I am coding one simple test using `@jackfranklin/test-data-bot` along with Typescript:

```typescript
import { build, fake } from "@jackfranklin/test-data-bot";

interface Account {
  balance: number;
}

const accountBuilder = build<Account>("Account", {
  fields: {
    balance: fake((f) => f.finance.amount()),
  },
});
```

However, importing `fake` from `@jackfranklin/test-data-bot` results in the following error:
```
Module '"@jackfranklin/test-data-bot"' has no exported member 'fake'.
```
![image](https://user-images.githubusercontent.com/47266830/166118796-6536e9b1-2ed7-412e-af2a-3c12f91f74b0.png)

Ignoring the error and using jest to test will result in the following output:
```
  ● Test suite failed to run

    TypeError: (0 , _testDataBot).fake is not a function

       8 | const accountBuilder = build<Account>("Account", {
       9 |   fields: {
    > 10 |     balance: fake((f) => f.finance.amount()),
         |                                             ^
      11 |   },
      12 | });
      13 |

      at Object.<anonymous> (features/dashboard/header/index.test.tsx:10:45)
      at TestScheduler.scheduleTests (node_modules/@jest/core/build/TestScheduler.js:317:13)    
      at runJest (node_modules/@jest/core/build/runJest.js:407:19)
      at _run10000 (node_modules/@jest/core/build/cli/index.js:338:7)
      at runCLI (node_modules/@jest/core/build/cli/index.js:190:3)

```

## Expected Behavior
To be able to import `fake` from the library

## Actual Behavior
`fake` is not exported.

## Steps to reproduce
Here is a CodeSandBox to reproduce the error:

[![Edit test-data-bot fake module](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/test-data-bot-fake-module-tfxj6d?fontsize=14&hidenavigation=1&module=%2Fsrc%2Findex.test.ts&previewwindow=tests&theme=dark)

**Comment by jackfranklin** [comment]
Hey, thanks for such a great bug report! 

The latest version of test-data-bot removed faker. You could either:

1. Downgrade to v1.4
2. Install faker yourself, and use the `perBuild` helper to run it:

```
const builder = build('User', {
  fields: {
    name: perBuild(() => /* call faker here with whatever random thing you want */),
  }
});
```

Please comment if you need any extra help. Thanks!

**Comment by RamonEspinosa** [comment]
@jackfranklin Some parts of the documentation seem to be outdated. If you need help with that, I could update the documentation so that no one runs into this issue again 🙂

**Comment by jackfranklin** [comment]
That would be awesome!
