### ISSUE TITLE
Composite builders do not increment sequence properly

### ISSUE THREAD

**Issue by djamiem** [jackfranklin/test-data-bot#847]
Hi - Love the library but ran into an issue when using a Builder within a Builder.

```js
const BaseUserBuilder = build<BaseUser>('BaseUser', {
fields: {
 id: sequence(),
 firstName: string,
 lastName: string
 }
}

const UserBuilder = build<User>('User', {
fields: {
 ...BaseUserBuilder(),
 someOtherField: string;
}
```

After running some unit tests on the code I noticed that doing the below fails and is expecting both ids to be 1: 

```js
 const user1 = UserBuilder();
 const user2 = UserBuilder();
 
 expect(user1.id).toBe(1);
 expect(user2.id).toBe(2);
```

Is doing a composite builder like this not a supported use case?

**Comment by jackfranklin** [comment]
Your issue here is that `...BaseUserBuilder()` will execute immediately, so every `UserBuilder` factory has a hardcoded id of `1` as that's what `sequence()` returns on the first call.

Does `postBuild` work for your use case?

```
const userBuilder = build('User', {
  fields: {
    someOtherField: 'whatever'
  },
  postBuild: user => {
    const newUser = {...BaseUser(), ...user};
    return newUser
  },
});

const user = userBuilder();
```

**Comment by jackfranklin** [comment]
I'm going to close this because I think with traits or postBuild funcs you can achieve this. Thanks!
