### ISSUE TITLE
is fake no longer exported from @jackfranklin/test-data-bot

### ISSUE THREAD

**Issue by Emmahchinonso** [jackfranklin/test-data-bot#856]
I'm currently on the version `^2.0.0` and it seems importing fake from `@jackfranklin/test-data-bot` is no longer possible.
I'm doing just this but fake seems undefined, any help please
```
import { build, fake } from "@jackfranklin/test-data-bot";

  const buildSignupForm = build({
    fields: {
      firstName: fake((f) => f.internet.name),
      email: fake((f) => f.internet.email),
      countryCode: "NGA",
    },
  });
  console.log(buildSignupForm());
```

**Comment by jackfranklin** [comment]
Yes, it is no longer included by default. See https://github.com/jackfranklin/test-data-bot/pull/603 for an example of how to integrate it yourself. Thanks!
