### ISSUE TITLE
Add API to create more than one object

### ISSUE THREAD

**Issue by Gpx** [jackfranklin/test-data-bot#894]
I often need to create more than one object for my tests. For example, if I'm testing a list of users, I will need a few. Currently, I do something like this:

```js
const users = [userBuilder(), userBuilder(), userBuilder()]
```

That's all right, but it becomes cumbersome if I want to create 20 users. So I have to resort to a loop of some sort.

It would be great to have some way to create more than one object at once. Something like this:

```js
const users = userBuilder.times(20)
// or
const users = userBuilder({ times: 20 })
```

Is this something that you consider useful/worth implementing?

**Comment by paulirish** [comment]
Jack's developing this feature live on twitch right now: https://www.twitch.tv/jackfcodes

**Comment by Gpx** [comment]
Loved the streaming, pity I missed it live. Thanks for doing this @jackfranklin!
